name: Run Docker Compose5

on:
  push:
    paths:
      - .github/workflows/main.yml

jobs:
  compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Optional, helps with Compose compatibility

    - name: Create .env file for sensitive variables
      run: |
        echo "TUNNEL_TOKEN=${{ secrets.TUNNEL_TOKEN }}" >> .env
        echo "OPENVPN_USER=${{ secrets.OPENVPN_USER }}" >> .env
        echo "OPENVPN_PASSWORD=${{ secrets.OPENVPN_PASSWORD }}" >> .env
        echo "SERVER_NAMES=${{ secrets.SERVER_NAMES }}" >> .env
        echo "SHADOWSOCKS_PASSWORD=${{ secrets.SHADOWSOCKS_PASSWORD }}" >> .env

    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "franeckn" --password-stdin
        docker compose -f docker-compose.yml up -d

    - name: Wait for services to be ready
      uses: jakejarvis/wait-action@master
      with:
        time: '200s'  # Adjust based on how long services take to start

    - name: Check container status
      run: |
        docker compose -f docker-compose.yml ps
        docker compose -f docker-compose.yml logs
